<a href="https://colab.research.google.com/github/Dheeraj16-code/labs-and-projects/blob/main/Dheeraj_Gundapuneni.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics of Linear Algebra

Import the Numpy library for linear Algebra functions and Matplotlib for some plotting functions.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

Transpose of a Matrix

Matrix transpose is performed with the transpose method on a nested on a nesrted list or a python array, or a higher dimensional Numpy array.

In [5]:
#Define matrices with different dimensions
a=np.array([[1,2],[3,4]])
b=np.array([[5,6,7],[8,9,10]])
#Calculate transposes
a_t=np.transpose(a)
b_t=np.transpose(b)
#print results
print("Matrix A:\n",a)
print("Transpose of A:\n",a_t)
print("Matrix B:\n",b)
print("Transpose of B:\n",b_t)

Matrix A:
 [[1 2]
 [3 4]]
Transpose of A:
 [[1 3]
 [2 4]]
Matrix B:
 [[ 5  6  7]
 [ 8  9 10]]
Transpose of B:
 [[ 5  8]
 [ 6  9]
 [ 7 10]]


If the matrix is a Numpy array,It can be treated as an object and method T can be applied over it as follows.

In [7]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
b=np.array([[1,2],[3,4],[5,6]])
print("Matrix A:\n",a)
print("Transpose of A:\n",a_t)
print("Matrix B:\n",b)
print("Transpose of B:\n",b_t)


Matrix A:
 [[1 2 3 4]
 [2 3 4 5]]
Transpose of A:
 [[1 3]
 [2 4]]
Matrix B:
 [[1 2]
 [3 4]
 [5 6]]
Transpose of B:
 [[ 5  8]
 [ 6  9]
 [ 7 10]]


The dot method of Numpy performs dot-matrix product(scalar product) for 1-d or higher dimensional arrays.If the inputs are scalars (numbers),It can performs multiplications.

In [10]:
#Scalars
import numpy as np
a=10
d=2
w=np.dot(a,d)
print("Dot product of Scalars:",w)

e=2
f=np.array([1,2,3])
g=e*f
print("Scalar Multiplication:",g)

Dot product of Scalars: 20
Scalar Multiplication: [2 4 6]


In [11]:
w=a*d
print(w)

20


In this case of one or higher dimensional arrays, the inputs can be either Numpy arrays,Python arrays or lists.

In [13]:
#1D ARRAYS
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Dot product:",np.dot(a,b))

#Experimental
c=[7,8,9]
d=[10,11,12]
print("Dot product:", np.dot(c,d))

Dot product: 32
Dot product: 266


In [16]:
# Assuming I want to perform operations on the matrices defined in the previous code.
# Example: Matrix addition

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])

# You can't directly add matrices of different dimensions.
# If you want to demonstrate matrix operations, provide compatible matrices.

# Example with compatible matrices:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_sum = matrix1 + matrix2
print("Matrix Sum:\n", matrix_sum)

# Example: Matrix multiplication
matrix_product = np.dot(matrix1, matrix2)
print("Matrix Product:\n", matrix_product)


Matrix Sum:
 [[ 6  8]
 [10 12]]
Matrix Product:
 [[19 22]
 [43 50]]


In [17]:
import numpy as np

def dot_product(a, b):
  """
  Calculates the dot product of two arrays or matrices.

  Args:
    a: The first array or matrix.
    b: The second array or matrix.

  Returns:
    The dot product of a and b. Returns an error message if the dot product is not defined
  """
  try:
    return np.dot(a, b)
  except ValueError as e:
    return f"Error: {e}"

# Example usage with different inputs
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(dot_product(a, b))  # Output: [[19 22] [43 50]]


c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

print(dot_product(c, d))  # Output: 32


e = np.array([[1, 2], [3, 4]])
f = np.array([5, 6, 7])

print(dot_product(e, f)) # Output: Error: shapes (2,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)


[[19 22]
 [43 50]]
32
Error: shapes (2,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)


we can obtain the same result using np.matmul().


NUMPY ARRAYS

In [19]:
#CONVERT LISTS IN TO NUMPY ARRAYS
import numpy as np

# Example lists
list1 = [1, 2, 3, 4, 5]
list2 = [[1, 2, 3], [4, 5, 6]]

# Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Print the arrays
print("Array 1:\n", array1)
print("Array 2:\n", array2)


Array 1:
 [1 2 3 4 5]
Array 2:
 [[1 2 3]
 [4 5 6]]


THE MULTI_DOT METHOD

In [20]:
# MATRICES WITH RANDOM INTEGERS ENTRIES RAGING FROM -4 TO 4

import numpy as np

# Generate matrices with random integer entries ranging from -4 to 4
def generate_random_matrix(rows, cols, min_val=-4, max_val=4):
    return np.random.randint(min_val, max_val + 1, size=(rows, cols))

# Example usage:
rows1 = 2
cols1 = 3
matrix1 = generate_random_matrix(rows1, cols1)
print("Matrix 1:\n", matrix1)


rows2 = 3
cols2 = 2
matrix2 = generate_random_matrix(rows2, cols2)
print("\nMatrix 2:\n", matrix2)

# ... (rest of your code)

# Example with different parameters
rows3 = 4
cols3 = 4
min_val = -10  # New minimum value
max_val = 10  # New maximum value
matrix3 = generate_random_matrix(rows3, cols3, min_val, max_val)

print(f"\nMatrix 3 (with min={min_val}, max={max_val}):\n{matrix3}")

# Example of matrix multiplication with the new matrix

if cols1 == rows2: # Check for compatibility for matrix multiplication
    product_matrix = np.dot(matrix1, matrix2)
    print("\nMatrix Product (Matrix1 * Matrix2):\n", product_matrix)
else:
    print("\nMatrix multiplication is not possible due to incompatible dimensions.")




Matrix 1:
 [[ 3 -1 -2]
 [ 1  2 -3]]

Matrix 2:
 [[-1  3]
 [-1 -4]
 [ 1  0]]

Matrix 3 (with min=-10, max=10):
[[ -6   3  -8 -10]
 [ -4  -8  -8  10]
 [  1  -1   9  10]
 [ -4   0   4  10]]

Matrix Product (Matrix1 * Matrix2):
 [[-4 13]
 [-6 -5]]


In [21]:
#INNER PRODUCT

import numpy as np
# Example usage with different parameters for generate_random_matrix
rows4 = 3
cols4 = 3
min_val = -2  # New minimum value
max_val = 2  # New maximum value
matrix4 = generate_random_matrix(rows4, cols4, min_val, max_val)

print(f"\nMatrix 4 (with min={min_val}, max={max_val}):\n{matrix4}")

# Example of matrix multiplication with the new matrix and existing ones

if cols1 == rows4:  # Check for compatibility
    product_matrix1 = np.dot(matrix1, matrix4)
    print("\nMatrix Product (Matrix1 * Matrix4):\n", product_matrix1)
else:
    print("\nMatrix multiplication (Matrix1 * Matrix4) is not possible due to incompatible dimensions.")

if cols2 == rows4: #check for compatibility
  product_matrix2 = np.dot(matrix2, matrix4)
  print("\nMatrix product (Matrix2 * Matrix4):\n", product_matrix2)
else:
    print("\nMatrix multiplication (Matrix2 * Matrix4) is not possible due to incompatible dimensions.")

if cols4 == rows1:
  product_matrix3 = np.dot(matrix4, matrix1)
  print("\nMatrix product (Matrix4 * Matrix1):\n", product_matrix3)
else:
    print("\nMatrix multiplication (Matrix4 * Matrix1) is not possible due to incompatible dimensions.")



Matrix 4 (with min=-2, max=2):
[[-2 -1 -2]
 [ 0  2  1]
 [-1  0  0]]

Matrix Product (Matrix1 * Matrix4):
 [[-4 -5 -7]
 [ 1  3  0]]

Matrix multiplication (Matrix2 * Matrix4) is not possible due to incompatible dimensions.

Matrix multiplication (Matrix4 * Matrix1) is not possible due to incompatible dimensions.


In [22]:
# OUTER PRODUCT

import numpy as np

def outer_product(a, b):
    """
    Calculates the outer product of two vectors.

    Args:
        a: The first vector (NumPy array).
        b: The second vector (NumPy array).

    Returns:
        The outer product of a and b (NumPy array), or an error message if the inputs are invalid.
    """
    try:
        return np.outer(a, b)
    except ValueError as e:
        return f"Error: {e}"

# Example usage
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

result = outer_product(vector1, vector2)
print(result)


vector3 = np.array([1, 2])
vector4 = np.array([3, 4, 5])
result2 = outer_product(vector3, vector4)
result2


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


array([[ 3,  4,  5],
       [ 6,  8, 10]])

Matrix Determinant

In [29]:
#  matrix determinant

import numpy as np

def matrix_determinant(matrix):
    """
    Calculates the determinant of a square matrix.

    Args:
        matrix: A NumPy array representing a square matrix.

    Returns:
        The determinant of the matrix, or an error message if the input is invalid.
    """
    try:
        return np.linalg.det(matrix)
    except np.linalg.LinAlgError:
        return "Error: Matrix is not square or singular."
    except ValueError:
        return "Error: Invalid input matrix."


# Example usage
matrix5 = np.array([[1, 2], [3, 4]])
det5 = matrix_determinant(matrix5)
print(f"\nDeterminant of Matrix 5:\n{det5}")

matrix6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det6 = matrix_determinant(matrix6)
print(f"\nDeterminant of Matrix 6:\n{det6}")

matrix7 = np.array([[1, 2], [3,4], [5,6]]) # Non-square matrix
det7 = matrix_determinant(matrix7)
print(f"\nDeterminant of Matrix 7:\n{det7}")

# Example with a singular matrix (determinant is zero)
singular_matrix = np.array([[1, 2], [2, 4]])
det_singular = matrix_determinant(singular_matrix)
print(f"\nDeterminant of singular matrix:\n{det_singular}")



Determinant of Matrix 5:
-2.0000000000000004

Determinant of Matrix 6:
0.0

Determinant of Matrix 7:
Error: Matrix is not square or singular.

Determinant of singular matrix:
0.0


Matrix Inverse

In [31]:
# prompt: matrix inverse by adding new parameters try to code in short lines of code

import numpy as np

def matrix_inverse(matrix):
    """Calculates the inverse of a square matrix.

    Args:
      matrix: A NumPy array representing a square matrix.

    Returns:
      The inverse of the matrix, or an error message if the input is invalid or the matrix is singular.
    """
    try:
        return np.linalg.inv(matrix)
    except np.linalg.LinAlgError:
        return "Error: Matrix is singular or not square."
    except ValueError:
        return "Error: Invalid input matrix."

# Example usage
matrix8 = np.array([[1, 2], [3, 4]])
inv8 = matrix_inverse(matrix8)
print(f"\nInverse of Matrix 8:\n{inv8}")

matrix9 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inv9 = matrix_inverse(matrix9)
print(f"\nInverse of Matrix 9:\n{inv9}")

singular_matrix = np.array([[1, 2], [2, 4]])
inv_singular = matrix_inverse(singular_matrix)  # Will print the error message
print(f"\nInverse of singular matrix:\n{inv_singular}")

# Example with different parameters for generate_random_matrix (from previous code)
rows = 3
cols = 3
min_val = -2
max_val = 2
matrix10 = np.random.randint(min_val, max_val + 1, size=(rows, cols))

print(f"\nMatrix 10:\n{matrix10}")
inv10 = matrix_inverse(matrix10)
print(f"\nInverse of Matrix 10:\n{inv10}")



Inverse of Matrix 8:
[[-2.   1. ]
 [ 1.5 -0.5]]

Inverse of Matrix 9:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Inverse of singular matrix:
Error: Matrix is singular or not square.

Matrix 10:
[[ 1  0 -2]
 [-1  1  2]
 [-1  0 -1]]

Inverse of Matrix 10:
[[ 0.33333333  0.         -0.66666667]
 [ 1.          1.          0.        ]
 [-0.33333333 -0.         -0.33333333]]


Power of matrix

In [32]:
 #POWER OF MATRIX
import numpy as np

def matrix_power(matrix, power):
    """
    Raises a square matrix to a given power.

    Args:
      matrix: A NumPy array representing a square matrix.
      power: The power to raise the matrix to (integer).

    Returns:
      The matrix raised to the given power, or an error message if the input is invalid.
    """
    try:
        if not isinstance(power, int):
            raise ValueError("Power must be an integer.")

        return np.linalg.matrix_power(matrix, power)
    except np.linalg.LinAlgError:
        return "Error: Matrix is not square or singular for power operation."
    except ValueError as e:
        return f"Error: {e}"


# Example usage
matrix11 = np.array([[1, 2], [3, 4]])
power = 3
result11 = matrix_power(matrix11, power)
print(f"\nMatrix 11 raised to power {power}:\n{result11}")

matrix12 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
power = 2
result12 = matrix_power(matrix12, power)
print(f"\nMatrix 12 raised to power {power}:\n{result12}")

# Example with a non-integer power
power = 2.5
result_invalid = matrix_power(matrix11, power)
print(f"\nResult with non integer power:\n{result_invalid}") # Expecting error message

# Example with a non-square matrix
non_square_matrix = np.array([[1, 2], [3, 4], [5, 6]])
power = 2
result_non_square = matrix_power(non_square_matrix, power) # Expecting error message
print(f"\nResult with non square matrix:\n{result_non_square}")



Matrix 11 raised to power 3:
[[ 37  54]
 [ 81 118]]

Matrix 12 raised to power 2:
[[16 22 11]
 [20 25  4]
 [ 5 16 39]]

Result with non integer power:
Error: Power must be an integer.

Result with non square matrix:
Error: Matrix is not square or singular for power operation.


Eigen values and eigen vectors

In [24]:
 #egien values and egien vectors of a matrices

import numpy as np

# Example matrix (you can change this)
A = np.array([[2, 1],
              [1, 2]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Experiment with different matrices:

# Example 1:  A diagonal matrix
A1 = np.array([[3, 0],
               [0, 1]])
eigenvalues1, eigenvectors1 = np.linalg.eig(A1)

print("\nEigenvalues (A1):", eigenvalues1)
print("Eigenvectors (A1):\n", eigenvectors1)


# Example 2:  A symmetric matrix
A2 = np.array([[2, -1],
              [-1, 2]])

eigenvalues2, eigenvectors2 = np.linalg.eig(A2)

print("\nEigenvalues (A2):", eigenvalues2)
print("Eigenvectors (A2):\n", eigenvectors2)


# Example 3: A 3x3 matrix
A3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

eigenvalues3, eigenvectors3 = np.linalg.eig(A3)

print("\nEigenvalues (A3):", eigenvalues3)
print("Eigenvectors (A3):\n", eigenvectors3)


Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Eigenvalues (A1): [3. 1.]
Eigenvectors (A1):
 [[1. 0.]
 [0. 1.]]

Eigenvalues (A2): [3. 1.]
Eigenvectors (A2):
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Eigenvalues (A3): [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors (A3):
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Trace of a matrix

In [25]:
# trace of a matrix

import numpy as np

def matrix_trace(matrix):
    """Calculates the trace of a square matrix.

    Args:
        matrix: A NumPy array representing a square matrix.

    Returns:
        The trace of the matrix, or an error message if the input is invalid.
    """
    try:
        if matrix.shape[0] != matrix.shape[1]:
            return "Error: Input matrix is not square."
        return np.trace(matrix)
    except AttributeError:
        return "Error: Input is not a NumPy array."
    except Exception as e:
        return f"An unexpected error occurred: {e}"


# Example usage with different matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Trace of matrix1:", matrix_trace(matrix1))

matrix2 = np.array([[1, 2], [3, 4]])
print("Trace of matrix2:", matrix_trace(matrix2))

# Example with a non-square matrix
matrix3 = np.array([[1, 2, 3], [4, 5, 6]])
print("Trace of matrix3:", matrix_trace(matrix3)) # Output: Error message

# Example with an invalid input
matrix4 = [[1, 2], [3, 4]]
print("Trace of matrix4:", matrix_trace(matrix4))  # Output: Error message

# Example with a larger matrix
matrix5 = np.random.rand(5,5) #Generate a random 5x5 matrix
print("Trace of matrix5:",matrix_trace(matrix5))


Trace of matrix1: 15
Trace of matrix2: 5
Trace of matrix3: Error: Input matrix is not square.
Trace of matrix4: Error: Input is not a NumPy array.
Trace of matrix5: 1.8553768548525817


Matrices Norm

In [34]:
# matrices norm

import numpy as np

def matrix_norm(matrix, order=2):
    """
    Calculates the matrix norm of a given matrix.

    Args:
        matrix: A NumPy array representing the matrix.
        order: The order of the norm (default is 2 for Frobenius norm).
               Can be 'inf' for the infinity norm or a positive integer.

    Returns:
        The matrix norm, or an error message if the input is invalid.
    """
    try:
        if order == 'inf':
            return np.linalg.norm(matrix, ord=np.inf)  # Infinity norm
        elif order == 2:
            return np.linalg.norm(matrix) # Frobenius norm
        elif isinstance(order, int) and order > 0:
            return np.linalg.norm(matrix, ord=order)
        else:
            return "Error: Invalid norm order."
    except ValueError as e:
        return f"Error: {e}"

# Examples
matrix = np.array([[1, 2], [3, 4]])

# Frobenius norm (order=2 or default)
frobenius_norm = matrix_norm(matrix)
print(f"Frobenius Norm: {frobenius_norm}")


# Infinity norm
infinity_norm = matrix_norm(matrix, order='inf')
print(f"Infinity Norm: {infinity_norm}")

# Other norms
norm_1 = matrix_norm(matrix, order=1)
print(f"1-Norm: {norm_1}")


Frobenius Norm: 5.477225575051661
Infinity Norm: 7.0
1-Norm: 6.0


Norm of Matrix

In [ ]:
# norm matrixes

import numpy as np

def matrix_norm(matrix, order=2):
    """Calculates the matrix norm."""
    try:
        return np.linalg.norm(matrix, ord=order)
    except ValueError as e:
        return f"Error: {e}"


Solving System of Equations

In [35]:
# solving the system of equations in matrices

import numpy as np

def solve_linear_system(A, b):
    """Solves a system of linear equations Ax = b.

    Args:
        A: A NumPy array representing the coefficient matrix.
        b: A NumPy array representing the constant vector.

    Returns:
        A NumPy array representing the solution vector x, or an error message if the system cannot be solved.
    """
    try:
        x = np.linalg.solve(A, b)
        return x
    except np.linalg.LinAlgError:
        return "Error: Singular matrix or inconsistent system."
    except ValueError:
        return "Error: Invalid input matrices."


# Example usage
A = np.array([[2, 1], [1, -1]])
b = np.array([5, 0])

solution = solve_linear_system(A, b)

if isinstance(solution, str):
  print(solution)
else:
  print("Solution:", solution)


# Another example
A = np.array([[1, 2], [2,4]])
b = np.array([3, 6])

solution = solve_linear_system(A, b)

if isinstance(solution, str):
  print(solution)
else:
  print("Solution:", solution)


# Example with singular matrix
A = np.array([[1, 2], [2, 4]])
b = np.array([3, 5]) # Inconsistent system
solution = solve_linear_system(A, b)

if isinstance(solution, str):
  print(solution)
else:
  print("Solution:", solution)


Solution: [1.66666667 1.66666667]
Error: Singular matrix or inconsistent system.
Error: Singular matrix or inconsistent system.


Singular value decomposition

In [42]:
#singular value decomposition of a matrix

import numpy as np

def svd(matrix):
    """
    Performs Singular Value Decomposition (SVD) on a matrix.

    Args:
        matrix: A NumPy array representing the matrix.

    Returns:
        A tuple containing U, S, and V, where:
            U: The left singular vectors.
            S: The singular values.
            V: The right singular vectors.
        Returns an error message if the input is invalid.
    """
    try:
        U, S, V = np.linalg.svd(matrix)
        return U, S, V
    except ValueError as e:
        return f"Error: {e}"
